[package]
name = "fastid"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "fastid"
crate-type = ["cdylib"]


[dependencies]
ulid="1.1.0"
pyo3="0.20.0"
rs-snowflake = "0.6.0"
once_cell = "1.19.0"
